WITH PURCHASE_ORDER_DATE 
AS(
    SELECT 
        PURCHASE_ORDER_ID,
        PURCHASE_ORDER_DATE
    FROM
        {{ ref('stg_purchase_orders') }}
),
PURCHASE_VALUE
AS(
    SELECT
        PO.PURCHASE_ORDER_ID,
        PURCHASE_ORDER_DATE,
        ITEM_CODE,
        BUYING_PRICE_OF_SINGLE_UNIT
    FROM
        {{ ref('stg_purchase_orderline') }} AS PO
    JOIN
        PURCHASE_ORDER_DATE AS POD
    ON
        PO.PURCHASE_ORDER_ID = POD.PURCHASE_ORDER_ID
),
MARGIN_VALUE
AS(
    SELECT
        ITEM_CODE,
        DATE_TRUNC('MONTH', PURCHASE_ORDER_DATE) AS ORDER_DATE,
        AVG(BUYING_PRICE_OF_SINGLE_UNIT) AS AVG_BUYING_PRICE
    FROM
        PURCHASE_VALUE AS PV
    GROUP BY
        ITEM_CODE,
        DATE_TRUNC('MONTH', PURCHASE_ORDER_DATE)
)
SELECT 
    *
FROM
    MARGIN_VALUE