WITH PRODUCT_TYPE_MONTHLY_REVENUE
AS(
    SELECT
        PRODUCT_TYPE,
        SUM(LINE_TOTAL_VALUE) AS LINE_VALUE,
        SUM(LINE_TAX_VALUE) AS LINE_TAX_VALUE,
        DATE_TRUNC('MONTH', INVOICE_DATE) AS MONTHLY
    FROM
        {{ ref('transform_product_invoice') }}
    GROUP BY
        PRODUCT_TYPE,
        DATE_TRUNC('MONTH', INVOICE_DATE)
)
SELECT
    PRODUCT_TYPE,
    MONTHLY,
    (LINE_VALUE-LINE_TAX_VALUE) AS TOTAL_VALUE_PRODUCT_TYPE_MONTHLY
FROM
    PRODUCT_TYPE_MONTHLY_REVENUE
ORDER BY
    MONTHLY,
    PRODUCT_TYPE
