WITH SPEND_PER_PRODUCT_QUARTERLY_REVENUE
AS(
    SELECT
        ITEM_CODE,
        SUM(LINE_TOTAL_VALUE) AS LINE_VALUE,
        SUM(LINE_TAX_VALUE) AS LINE_TAX_VALUE,
        DATE_TRUNC('QUARTER', INVOICE_DATE) AS QUARTERLY
    FROM
        {{ ref('transform_product_invoice') }}
    GROUP BY
        ITEM_CODE,
        DATE_TRUNC('QUARTER', INVOICE_DATE)
)
SELECT
    QUARTERLY,
    ITEM_CODE,
    (LINE_VALUE-LINE_TAX_VALUE) AS TOTAL_VALUE_PER_PRODUCT_QUARTERLY 
FROM
    SPEND_PER_PRODUCT_QUARTERLY_REVENUE
ORDER BY
    QUARTERLY