WITH PURCHASE_ORDERS_DATA
AS(
    SELECT
        PURCHASEORDERID AS PURCHASE_ORDER_ID,
        PURCHASEORDERNUMBER AS PURCHASE_ORDER_NUMBER,
        CAST(PURCHASEORDERDATE AS DATE) AS PURCHASE_ORDER_DATE,
        CAST(CRETAEDDATE AS DATE) AS CREATED_DATE,
        CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE
    FROM
        {{ source('sales', 'PURCHASEORDERS') }}
)
SELECT 
    *
FROM    
    PURCHASE_ORDERS_DATA