WITH PRODUCT_GROUP_DATA
AS(
     SELECT
        ITEMID AS ITEM_ID,
        CAST(CODE AS VARCHAR(50) ) AS ITEM_CODE,
        PRODUCTGROUPID AS PRODUCT_GROUP_ID,
        CAST(PRODUCTGROUP AS VARCHAR(50)) AS PRODUCT_GROUP,
        CAST(PRODUCTTYPE AS VARCHAR(50)) AS PRODUCT_TYPE
    FROM
        {{ source('sales', 'PRODUCTGROUP') }}
    )
SELECT 
    *
FROM
    PRODUCT_GROUP_DATA