WITH DEVICES_DATA
AS(
    SELECT 
        ITEMID AS ITEM_ID,
        CAST(ITEMNAME AS VARCHAR(150)) AS ITEM_NAME,
        CAST(ITEMCODE AS VARCHAR(150)) AS ITEM_CODE,
        CAST(MANUFACTURER AS VARCHAR(150)) AS MANUFACTURER,
        PRODUCTGROUPID AS PRODUCT_GROUP_ID,
        CAST(CRETAEDDATE AS DATE) AS CREATED_DATE,
        CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE
    FROM
        {{ source('sales', 'DEVICES') }}
)
SELECT
    *
FROM
    DEVICES_DATA