WITH INVOICE_LINE
AS(
    SELECT
        INVOICELINEID AS INVOICE_LINE_ID,
        INVOICEID AS INVOICE_ID,
        SEQUENCENUMBER AS SEQUENCE_NUMBER,
        ORDERLINEID AS ORDER_LINE_ID,
        CAST(INVOICEQUANTITY AS INT) AS INVOICE_QUANTITY,
        CAST(INVOICEDATE AS DATE) AS INVOICE_DATE,
        LINETOTALVALUE AS LINE_TOTAL_VALUE,
        LINETAXVALUE AS LINE_TAX_VALUE,
        CAST(ITEMPRICE AS DECIMAL) AS ITEM_PRICE,
        CAST(ITEMCODE AS VARCHAR(50)) AS ITEM_CODE,
        CAST(CRETAEDDATE AS DATE) AS CREATED_DATE,
        CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE
    FROM 
        {{ source('sales', 'INVOICELINE') }}
)
SELECT 
    *
FROM
    INVOICE_LINE