WITH PURCHASE_ORDER_LINE_DATA
AS(
    SELECT
        PURCHASEORDERID AS PURCHASE_ORDER_ID,
        PURCHASEORDERLINEID AS PURCHASE_ORDER_LINE_ID,
        CAST(ITEMCODE AS VARCHAR(50)) AS ITEM_CODE,
        CAST(BUYINGPRICEOFSINGLEUNIT AS DECIMAL) AS BUYING_PRICE_OF_SINGLE_UNIT,
        CAST(QUANTITY AS INT) AS QUANTITY,
        CAST(TAXVALUE AS DECIMAL) AS TAX_VALUE,
        SEQUENCENUMBER AS SEQUENCE_NUMBER,
        CAST(CRETAEDDATE AS DATE) AS CREATED_DATE,
        CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE
    FROM
        {{ source('sales', 'PURCHASEORDERLINE') }}

)
SELECT
    *
FROM
    PURCHASE_ORDER_LINE_DATA