WITH REVENUE_PER_PROJECT
AS(
    SELECT
        PROJECT_NUMBER,
        SUM(NET_VALUE-TAX_VALUE) AS GROSS_PROJECT_REVENUE
    FROM
        {{ ref('stg_sales_orders') }}
    GROUP BY
        PROJECT_NUMBER
)
SELECT
    *
FROM
    REVENUE_PER_PROJECT
ORDER BY
    GROSS_PROJECT_REVENUE DESC