WITH INVOICE_LINE_PRICE
AS(
    SELECT
        ITEM_CODE,
        SUM(ITEM_PRICE) AS MONTHLY_ITEM_PRICE,
        DATE_TRUNC('MONTH', INVOICE_DATE) AS INVOICE_DATE,
    FROM 
        {{ ref('stg_invoice_line_data') }} AS IL
    GROUP BY
        ITEM_CODE,
        DATE_TRUNC('MONTH', INVOICE_DATE)
),
PRUCHASE_INVOICE 
AS(
    SELECT
        IL.ITEM_CODE,
        INVOICE_DATE,
        MONTHLY_ITEM_PRICE,
        AVG_BUYING_PRICE,
        {{ profit_margin_percentage('MONTHLY_ITEM_PRICE', 'AVG_BUYING_PRICE') }}  AS MARGIN_VALUE,
        DATE_TRUNC('MONTH', INVOICE_DATE) AS INVOICE_DATE
    FROM 
       INVOICE_LINE_PRICE AS IL
    JOIN
        {{ ref('transform_margin_sales') }} AS PO
    ON
        IL.ITEM_CODE = PO.ITEM_CODE
    AND
        IL.INVOICE_DATE=PO.ORDER_DATE
),
MARGIN_PROUDCT_TYPE_GROUP
AS(
    SELECT
        PRODUCT_GROUP,
        PRODUCT_TYPE,
        SUM(MARGIN_VALUE) AS MARGIN_VALUE
    FROM
        PRUCHASE_INVOICE AS IL
    JOIN
        {{ ref('stg_product_group') }} AS P
    ON
        IL.ITEM_CODE = P.ITEM_CODE
    GROUP BY
        PRODUCT_GROUP,
        PRODUCT_TYPE
)
SELECT
    * 
FROM
    MARGIN_PROUDCT_TYPE_GROUP