WITH SALES_COMPUTE
AS(
    SELECT
        PROJECT_NUMBER,
        SUM(NET_VALUE) AS ORD_NET_VALUE,
        SUM(AVG_BUYING_PRICE)  AS AVG_BUYING_PRICE,
        MIN(ORDER_DATE) AS FIRST_ORDER_DATE
    FROM 
        {{ ref('transform_sales_details') }}
    GROUP BY
        PROJECT_NUMBER
),
SALES_DATE
AS(
    SELECT 
        PROJECT_NUMBER,
        ORDER_DATE,
        NET_VALUE
    FROM 
        {{ ref('transform_sales_details') }}
),
POST_PROFIT
AS(
    SELECT 
        SALES_COMPUTE.PROJECT_NUMBER,
        ROUND(SUM(ORD_NET_VALUE - AVG_BUYING_PRICE),2)AS POST_PROFIT
    FROM
        SALES_COMPUTE
    JOIN
        SALES_DATE
    ON
        SALES_COMPUTE.PROJECT_NUMBER = SALES_DATE.PROJECT_NUMBER
    WHERE 
        SALES_DATE.ORDER_DATE > FIRST_ORDER_DATE + INTERVAL '90 days'
    GROUP BY 
        SALES_COMPUTE.PROJECT_NUMBER
)   
SELECT 
    *
FROM
    POST_PROFIT
ORDER BY
    POST_PROFIT DESC