WITH PRODUCT_TYPE_YEARLY_REVENUE
AS(
    SELECT
        PRODUCT_TYPE,
        SUM(LINE_TOTAL_VALUE) AS LINE_VALUE,
        SUM(LINE_TAX_VALUE) AS LINE_TAX_VALUE,
        DATE_TRUNC('YEAR', INVOICE_DATE) AS YEARLY
    FROM
        {{ ref('transform_product_invoice') }}
    GROUP BY
        PRODUCT_TYPE,
        DATE_TRUNC('YEAR', INVOICE_DATE)
)
SELECT
    PRODUCT_TYPE,
    YEARLY,
    (LINE_VALUE-LINE_TAX_VALUE) AS TOTAL_VALUE_PRODUCT_TYPE_YEARLY
FROM
    PRODUCT_TYPE_YEARLY_REVENUE
ORDER BY
    YEARLY,
    PRODUCT_TYPE
