WITH SPEND_PER_PRODUCT_YEARLY_REVENUE
AS(
    SELECT
        ITEM_CODE,
        SUM(LINE_TOTAL_VALUE) AS LINE_VALUE,
        SUM(LINE_TAX_VALUE) AS LINE_TAX_VALUE,
        DATE_TRUNC('YEAR', INVOICE_DATE) AS YEARLY
    FROM
        {{ ref('transform_product_invoice') }}
    GROUP BY
        ITEM_CODE,
        DATE_TRUNC('YEAR', INVOICE_DATE)
)
SELECT
    YEARLY,
    ITEM_CODE,
    (LINE_VALUE-LINE_TAX_VALUE) AS TOTAL_VALUE_PER_PRODUCT_YEARLY 
FROM
    SPEND_PER_PRODUCT_YEARLY_REVENUE
ORDER BY
    YEARLY